import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // Seed Events
  await prisma.event.deleteMany();
  await prisma.event.createMany({
    data: [
      {
        slug: "enterprise-pyspark-kafka-databricks",
        title: "Enterprise Data Streaming with PySpark, Apache Kafka & Databricks",
        category: "upcoming",
        date: "Aug 15, 2026",
        time: "06:00 PM - 08:30 PM IST",
        mode: "JVM Pune Campus & Online",
        speakerName: "Rahul Deshmukh",
        speakerRole: "Principal Data Architect",
        speakerCompany: "Tier-1 Cloud Enterprise",
        speakerAvatar: "/place1.png",
        description: "Learn how to architect end-to-end real-time data streaming pipelines using PySpark Structured Streaming, Apache Kafka topics, and Delta Lake on Databricks with hands-on code walkthrough.",
        tags: ["PySpark", "Apache Kafka", "Databricks", "Data Streaming", "Delta Lake"],
        seatsTotal: 250,
        seatsFilled: 218,
        isFeatured: true,
      },
      {
        slug: "snowflake-modern-data-warehousing",
        title: "Snowflake Modern Data Warehousing & Zero-Copy Cloning Masterclass",
        category: "upcoming",
        date: "Aug 22, 2026",
        time: "11:00 AM - 01:30 PM IST",
        mode: "Virtual (Zoom Live)",
        speakerName: "Priya Sharma",
        speakerRole: "Senior Snowflake Consultant",
        speakerCompany: "Global Tech Solutions",
        speakerAvatar: "/place2.png",
        description: "Master Snowflake virtual warehouses, Micro-partitioning, Time Travel, Dynamic Tables, and Cost Optimization strategies used by Fortune 500 companies.",
        tags: ["Snowflake", "Data Warehousing", "SQL", "Cloud Data", "Time Travel"],
        seatsTotal: 300,
        seatsFilled: 245,
      },
      {
        slug: "jvm-tech-a-thon-2026",
        title: "JVM Tech-a-Thon 2026: 48-Hour National Data Engineering Hackathon",
        category: "hackathon",
        date: "Sep 05 - Sep 07, 2026",
        time: "Starts 06:00 PM IST",
        mode: "Hybrid",
        speakerName: "JVM Technical Board",
        speakerRole: "Hackathon Jury & Mentors",
        speakerCompany: "JVM Institute",
        speakerAvatar: "/jvm logo.jpeg",
        description: "Compete against India's top tech talent to build high-scale analytics engines & GenAI RAG applications. Prize Pool worth ₹1,00,000 + direct interview calls!",
        tags: ["Hackathon", "PySpark", "GenAI", "SQL", "AWS", "Snowflake"],
        seatsTotal: 500,
        seatsFilled: 380,
      },
    ],
  });

  // Seed Placements from jvm.imgs.docx
  await prisma.placement.deleteMany();
  await prisma.placement.createMany({
    data: [
      {
        name: "Dhiraj Dande",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Accenture / TCS / Deloitte",
        package: "24.75 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: "Being from an IT background, I wanted to enhance my Data Engineering skills and move to higher-paying opportunities. I joined JVM Institute to upgrade my expertise in SQL, Python, PySpark, AWS, and modern Data Engineering technologies. The structured learning, real-time projects, and interview preparation helped me strengthen my technical skills and confidence. As a result, I received multiple offers from leading companies: Accenture \u2013 24.75 LPA, TCS \u2013 23 LPA, Deloitte \u2013 23 LPA.",
      },
      {
        name: "Pranoti Thorat",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Coforge",
        package: "22.5 LPA",
        image: "/placements/placement_26_pranotithorat.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " I joined JVM Institute to upgrade my Data Engineering skills and prepare for better career opportunities. The trainers provided excellent guidance, practical knowledge, and continuous support throughout my learning journey. The mock interviews, assignments, and real-time project discussions helped me build confidence and improve my technical skills. The placement support was outstanding and played a key role in my success. I am grateful to JVM Institute for helping me achieve multiple opportunities with leading companies. Thank you to the entire JVM team for their dedication and support in my career growth.",
      },
      {
        name: "Parth Ghodekar",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "I Come From An It Background And Wanted To Achieve Better Career Growth In Data Engineering. To Upgrade My Skills, I Joined Jvm Institute And Gained Hands-On Experience In Sql, Python, Pyspark, Cloud, And Big Data Technologies. The Structured Training, Mock Interviews, And Continuous Support Helped Me Strengthen My Technical Knowledge And Confidence. With Consistent Effort And Guidance From The Jvm Team, I Secured An Offer From *Tcs As An It Analyst With 18.25 Lpa. Later, I Achieved Another Milestone By Receiving An Offer From **Ey With A Package Of 20 Lpa*. Thank You Jvm Institute For Helping Me Reach The Next Level In My Career.",
        package: "20 LPA",
        image: "/placements/placement_29_parthghodekar.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: "The practical training, live projects, and continuous mentorship at JVM Institute played a crucial role in enhancing my technical skills and landing my dream IT job.",
      },
      {
        name: "Rushabh Deshmukh",
        domain: "Data Engineering",
        placedRole: "Senior Data Engineer",
        company: "Quantiphi",
        package: "18.25 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: "After spending a few years preparing for government exams, I decided to explore opportunities in the IT industry. Coming from a non-IT background, I was unsure how to start my career transition. JVM Institute helped me build a strong foundation in Data Engineering with practical training in SQL, Python, PySpark, and AWS.",
      },
      {
        name: "Kranti Waghmare",
        domain: "Data Engineering",
        placedRole: "Senior Lead",
        company: "HCL Tech",
        package: "18 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: "I joined JVM Institute to upgrade my skills in Data Engineering, and it was a great learning experience. The trainers explain concepts in a simple and practical way with hands-on projects. Regular mock interviews and doubt-solving sessions helped me gain confidence.",
      },
      {
        name: "Mrudula Deshmukh",
        domain: "Data Engineering",
        placedRole: "Senior Data Engineer",
        company: "Photon / Cognizant / HCLTech",
        package: "17 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: "I was already working in the IT industry, but I wanted to upgrade my skills and move into the Data Engineering domain with better career opportunities. The knowledge and guidance provided by JVM Institute helped me crack multiple interviews and receive offers from top companies like Cognizant (16 LPA), Photon (17 LPA), and HCLTech (15.5 LPA).",
      },
      {
        name: "Rushikesh Kulkarni",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Tech Mahindra",
        package: "16.5 LPA",
        image: "/placements/placement_23_rushikeshkulkarni.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " I joined JVM Institute to upgrade my skills and stay updated with the latest industry technologies. The training was practical, well-structured, and focused on real-world applications. The trainers were highly knowledgeable and always ready to help with doubts. The hands-on assignments and mock interviews helped me improve both my technical and professional skills. I gained confidence in technologies like SQL, Python, PySpark, and Cloud platforms. The learning experience was excellent and added great value to my career growth. Thank you, JVM Institute, for helping me enhance my skills and advance my career.",
      },
      {
        name: "Ajinkya",
        domain: "Data Engineering",
        placedRole: "Senior Data Engineer",
        company: "Lti Mindtree",
        package: "16 LPA",
        image: "/placements/placement_5_ajinkya.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " I joined JVM Institute to upgrade my technical skills and improve my career prospects. The curriculum covered everything from SQL and Python to Cloud and Big Data technologies. The trainers were knowledgeable, supportive, and always encouraged us to learn beyond the classroom. The placement support and interview guidance were outstanding. It was truly a career-changing experience for me",
      },
      {
        name: "Shreyas",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Tiger Analytics",
        package: "15 LPA",
        image: "/placements/placement_18_shreyas.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " I joined JVM Institute to upgrade my skills and stay updated with the latest technologies in Data Engineering. The course covered SQL, Python, PySpark, AWS, Azure, and GCP in a practical way with hands-on projects and real-time examples. The trainers were highly supportive and always available to clear doubts. The structured learning approach, assignments, and mock interviews helped me strengthen my technical knowledge and confidence. Thanks to JVM Institute, I have significantly improved my skills and am better prepared for new career opportunities and professional growth. I highly recommend JVM Institute to anyone looking to enhance their Data Engineering expertise.",
      },
      {
        name: "Shilpa Shinde",
        domain: "Data Engineering",
        placedRole: "Consultant",
        company: "Capgemini",
        package: "14 LPA",
        image: "/placements/placement_20_shilpashinde.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " JVM Institute is a great place for professionals who want to upgrade their skills. The course content is relevant to current industry requirements, and the trainers provide excellent mentorship. The hands-on approach to learning helped me gain confidence and practical knowledge. I am grateful for the support and guidance provided by the entire team.",
      },
      {
        name: "Rohini",
        domain: "Data Engineering",
        placedRole: "Lead Software Engineer",
        company: "Persistent",
        package: "13.66 LPA",
        image: "/placements/placement_8_rohini.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " Coming from a non-IT background, I always dreamed of building a successful career in the technology industry but wasn't sure where to begin. JVM Institute provided me with the right guidance, structured learning path, and practical exposure through real-time projects. The trainers were incredibly supportive and helped me understand complex concepts in a simple way. The mock interviews, resume preparation, and continuous mentorship boosted my confidence and made me industry-ready. With the skills and knowledge gained at JVM Institute, I successfully secured a position as a Lead Software Engineer at Persistent with a package of 13.66 LPA. I am truly grateful to JVM Institute for helping me transform my career and achieve this milestone",
      },
      {
        name: "Jayshree",
        domain: "Data Engineering",
        placedRole: "Senior Consultant",
        company: "Ey",
        package: "13.5 LPA",
        image: "/placements/placement_14_jayshree.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " I come from a non-IT background and was looking for a way to build a career in the IT industry. After joining JVM Institute's Data Engineering course, my journey completely changed. The trainers explained every concept from the basics, making it easy for me to understand technologies like SQL, Python, Big Data, AWS, Azure, and PySpark. The live classes, daily assignments, mock interviews, and continuous support helped me gain confidence and improve my technical skills. The placement guidance and interview preparation sessions were especially helpful in making me job-ready. Today, I have successfully transitioned into the IT field, something I once thought was very difficult. I am grateful to JVM Institute and the entire team for their support, guidance, and dedication. I highly recommend JVM Institute to anyone looking to start or upgrade their career in Data Engineering.",
      },
      {
        name: "Saurabh Kumatkar",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Lumiq",
        package: "13.5 LPA",
        image: "/placements/placement_22_saurabhkumatkar.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " JVM Institute helped me bridge my skill gap and gain hands-on experience with industry-relevant tools and technologies. The trainers are experienced, supportive, and dedicated to student success. The training improved my confidence and technical abilities. Thank you JVM Institute for this wonderful learning experience.",
      },
      {
        name: "Vaishnavi Kadam",
        domain: "Data Engineering",
        placedRole: "Senior Data Engineer",
        company: "Quantiphi",
        package: "13.25 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " I wanted to move into a high-demand technology field and JVM Institute made the journey easy. The trainers explained every concept clearly and helped me build strong Data Engineering skills.",
      },
      {
        name: "Satyajeet",
        domain: "Data Engineering",
        placedRole: "Lead Software Engineer",
        company: "Persistent",
        package: "13.2 LPA",
        image: "/placements/placement_7_satyajeet.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " After spending several years in the preparing for goverment exams, I wanted a career with better growth opportunities. JVM Institute helped me learn industry-relevant technologies such as SQL, Python, AWS, and PySpark. The trainers provided personal attention and cleared every doubt patiently. The practical assignments and placement support made a huge difference. I successfully switched from Banking to IT and started my Data Engineering career.",
      },
      {
        name: "Twinkle Chopda",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Volkswagen Group",
        package: "13 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: "Being a Civil Engineer, I was looking for better career growth opportunities. JVM Institute helped me upskill in Data Engineering and guided me through interviews. Today, I am proud to have successfully transitioned into the IT industry.",
      },
      {
        name: "Aditya Abhyankar",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Neutrino",
        package: "13 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: "I was working at TCS with a lower package and wanted better career growth. Joining JVM Institute was a turning point in my career. The Data Engineering training was practical and industry-focused.",
      },
      {
        name: "Praful Deshmukh",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Merkle / Ex-Infosys",
        package: "13 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: "I was working at Infosys and wanted to upgrade my skills to move into a better Data Engineering role. Joining JVM Institute was one of the best decisions for my career growth.",
      },
      {
        name: "Prathamesh",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Zorba Consulting",
        package: "13 LPA",
        image: "/placements/placement_3_prathamesh.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: true,
        testimonial: " My journey with JVM Institute has been truly life-changing. The training program provided in-depth knowledge of SQL, Python, PySpark, AWS, Azure, and real-time Data Engineering projects. The trainers were highly supportive and ensured that every concept was understood clearly through practical implementation. The mock interviews, resume preparation, and placement support helped me build confidence and perform well in interviews. With the guidance of JVM Institute, I successfully secured multiple offers from leading companies including Zorba Consulting (13 LPA), Datametica (12.2 LPA), and IPG Mediabrands (12 LPA). I am sincerely grateful to JVM Institute for helping me achieve these career milestones and would highly recommend it to anyone aspiring to build a successful career in Data Engineering.",
      },
      {
        name: "Sayali Karpe",
        domain: "Cloud & Snowflake",
        placedRole: "Senior Gcp Data Engineer",
        company: "I Stayed At Home For A Long Time Searching For A Job But Was Unable To Find The Right Opportunity. I Was Worried About My Career And Unsure Of What To Do Next. That'S When I Found Jvm Institute And Decided To Enroll In Their Data Engineering Course. The Trainers Guided Me From The Basics And Helped Me Build Strong Technical Skills. With Their Training, Mock Interviews, And Placement Support, I Gained Confidence And Industry-Ready Knowledge. Today, I Am Successfully Placed In The It Industry With A High Package. Thank You, Jvm Institute, For Completely Transforming My Career.",
        package: "13 LPA",
        image: "/placements/placement_30_sayalikarpe.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "cloud_snowflake",
        isFeatured: true,
        testimonial: "The practical training, live projects, and continuous mentorship at JVM Institute played a crucial role in enhancing my technical skills and landing my dream IT job.",
      },
      {
        name: "Ankit",
        domain: "Data Engineering",
        placedRole: "Senior Consultant",
        company: "Mindcraft",
        package: "12.75 LPA",
        image: "/placements/placement_10_ankit.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " My experience with JVM Institute was fantastic. The trainers not only taught technical concepts but also guided us on resume building and interview preparation. The hands-on assignments and projects strengthened my practical knowledge. The supportive learning environment kept me motivated throughout the course. Thanks to JVM Institute, I was able to achieve my career goals successfully.",
      },
      {
        name: "Ruchi Bhoyar",
        domain: "Data Engineering",
        placedRole: "Senior Software Engineer",
        company: "Incedo",
        package: "12.5 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: "My journey from Marketing to Data Engineering was truly life-changing with JVM Institute. Coming from a marketing background, I had no technical knowledge and was unsure how to enter the IT industry.",
      },
      {
        name: "Shweta",
        domain: "Data Engineering",
        placedRole: "Software Engineer",
        company: "Persistent",
        package: "12.5 LPA",
        image: "/placements/placement_2_shweta.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " After a career break, I wanted to restart my professional journey in a growing field. JVM Institute gave me the confidence and skills needed to enter the IT industry. The trainers were extremely supportive and explained every topic in a simple manner. The live projects and interview preparation sessions helped me gain practical experience. Today, I am successfully working in the Data Engineering domain and grateful to JVM Institute for making this transition possible",
      },
      {
        name: "Kamran Shaikh",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Impetus",
        package: "12.5 LPA",
        image: "/placements/placement_19_kamranshaikh.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: "I To advance my career, I wanted to upgrade my skills, and JVM Institute exceeded my expectations. The training sessions were interactive, practical, and highly informative. The trainers were always available to guide and motivate us. I gained valuable knowledge and confidence that will help me in my professional journey. Highly recommended for skill enhancement.",
      },
      {
        name: "Sonam Ugale",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "PwC",
        package: "12 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: "Coming from a non-technical background, I had very little knowledge of Data Engineering and was unsure about my career transition. The trainers at JVM Institute guided me step by step.",
      },
      {
        name: "Deepali Lahange",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Randstad",
        package: "12 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: "I wanted to upskill myself in the latest Data Engineering technologies, and JVM Institute was the right choice. The learning environment is very supportive and interactive.",
      },
      {
        name: "Abhishek",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Datemetica",
        package: "12 LPA",
        image: "/placements/placement_4_abhishek.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " I joined JVM Institute to upgrade my technical skills and improve my career prospects. The curriculum covered everything from SQL and Python to Cloud and Big Data technologies. The trainers were knowledgeable, supportive, and always encouraged us to learn beyond the classroom. The placement support and interview guidance were outstanding. It was truly a career-changing experience for me.",
      },
      {
        name: "Pooja",
        domain: "Data Engineering",
        placedRole: "Developer",
        company: "Wipro",
        package: "12 LPA",
        image: "/placements/placement_12_pooja.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " entering the software industry seemed challenging at first. JVM Institute's structured training program and practical learning approach made the transition smooth and achievable. The trainers patiently guided me through every concept and provided constant support throughout the course. The interview preparation sessions and real-world projects helped me develop the skills required by top companies. Today, I am proud to have secured a Developer role at Wipro with a package of 12 LPA. I sincerely thank JVM Institute for helping me build a successful IT career.",
      },
      {
        name: "Sanket Pawar",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Programming.Com",
        package: "12 LPA",
        image: "/placements/placement_21_sanketpawar.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " I joined JVM Institute to upgrade my skills and strengthen my knowledge in Data Engineering. The trainers provided excellent guidance, practical learning, and continuous support throughout the course. The hands-on assignments, mock interviews, and real-time scenarios helped me build confidence and improve my technical skills. The placement support was outstanding and helped me secure multiple opportunities with reputed companies. I am grateful to the entire JVM team for their dedication and mentorship. Thank you, JVM Institute, for playing a key role in my career growth and success",
      },
      {
        name: "Shripad Joshi",
        domain: "Cloud & Snowflake",
        placedRole: "Gcp Data Engineer",
        company: "Vodafone",
        package: "11.75 LPA",
        image: "/placements/placement_25_shripadjoshi.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "cloud_snowflake",
        isFeatured: false,
        testimonial: " JVM Institute provides excellent training with supportive trainers and practical learning. The concepts are explained clearly, and the placement guidance is very helpful. Thank you JVM Institute for helping me enhance my skills and grow my career.",
      },
      {
        name: "Pruthviraj",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Dataeaze",
        package: "11.6 LPA",
        image: "/placements/placement_17_pruthviraj.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " As a non-IT student, I was initially worried about entering the IT industry. However, JVM Institute provided excellent training and continuous support at every step. The trainers were knowledgeable, patient, and always ready to help. The practical approach to learning helped me understand concepts quickly. The mock interviews and placement assistance were extremely valuable. Today, I feel confident in my technical skills and career path. Thank you, JVM Institute, for helping me achieve my goal.",
      },
      {
        name: "Priya",
        domain: "Data Engineering",
        placedRole: "Senior Data Engineer",
        company: "Cymetrix",
        package: "11.54 LPA",
        image: "/placements/placement_1_priya.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " Coming from a non-IT background, I was unsure about switching careers. JVM Institute made the transition smooth with their step-by-step training approach. The live projects gave me valuable practical exposure, and the trainers continuously motivated me throughout the course. Their placement assistance and mock interviews were incredibly helpful. Thanks to JVM Institute, I successfully started my journey in the IT industry.",
      },
      {
        name: "Ishika Pandit",
        domain: "Data Engineering",
        placedRole: "Consultant",
        company: "Capco",
        package: "11.5 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " JVM Institute has been a great platform for enhancing my technical skills. The course content is up-to-date, and the trainers explain concepts with real-world examples. The learning environment is supportive, and the regular practice sessions helped me improve significantly. Thank you JVM Institute for helping me take my skills to the next level.",
      },
      {
        name: "Atharv Patil",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Top IT Enterprise",
        package: "11.25 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: "The practical training, live projects, and continuous mentorship at JVM Institute played a crucial role in enhancing my technical skills and landing my dream IT job.",
      },
      {
        name: "Nikhil",
        domain: "Data Engineering",
        placedRole: "Senior Software Engineer",
        company: "Prodapt",
        package: "11 LPA",
        image: "/placements/placement_6_nikhil.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " I am extremely grateful to JVM Institute for helping me achieve this milestone in my career. The practical training, real-time projects, and continuous mentorship played a crucial role in enhancing my technical skills. The trainers were always supportive and guided me throughout the learning journey. The mock interviews and placement assistance boosted my confidence and prepared me for opportunities in top companies. Thanks to JVM Institute, I successfully received offers from Prodapt (11 LPA) and Senzcraft (10 LPA). I highly recommend JVM Institute to anyone looking to build a successful career in the IT industry",
      },
      {
        name: "Vaishnavi",
        domain: "Data Engineering",
        placedRole: "Technical Lead",
        company: "Hcl Tech",
        package: "11 LPA",
        image: "/placements/placement_11_vaishnavi.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " I came from a non-IT background with a strong desire to build a career in technology. JVM Institute helped me bridge the gap with hands-on training, practical assignments, and expert mentorship. The trainers focused on real-world scenarios and ensured that every concept was understood thoroughly. The placement support and mock interviews prepared me to confidently face recruitment challenges. Thanks to JVM Institute, I successfully secured a Technical Lead position at HCLTech with a package of 11 LPA. This achievement would not have been possible without their guidance and support.",
      },
      {
        name: "Kartik",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Code Chavo",
        package: "11 LPA",
        image: "/placements/placement_13_kartik.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " Coming from a non-IT background, I was uncertain about how to start my journey in the technology field. JVM Institute provided me with the right guidance, practical training, and industry-focused learning. The trainers helped me build a strong foundation in SQL, Python, PySpark, and Cloud technologies through real-time projects. The mock interviews and placement support significantly improved my confidence. With the continuous mentorship from JVM Institute, I successfully secured a Data Engineer position at CodeChavo with a package of 11 LPA. I am thankful to JVM Institute for helping me achieve this career transformation.",
      },
      {
        name: "Aarti Shinde",
        domain: "Data Engineering",
        placedRole: "Senior Software Developer",
        company: "Hcl Tech",
        package: "11 LPA",
        image: "/placements/placement_15_aartishinde.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " I joined JVM Institute to upgrade my skills and stay updated with the latest industry technologies. The training was practical, well-structured, and focused on real-world applications. The trainers were highly knowledgeable and always ready to help with doubts. The hands-on assignments and mock interviews helped me improve both my technical and professional skills. I gained confidence in technologies like SQL, Python, PySpark, and Cloud platforms. The learning experience was excellent and added great value to my career growth. Thank you, JVM Institute, for helping me enhance my skills and advance my career.",
      },
      {
        name: "Deepti Shengule",
        domain: "Data Analytics",
        placedRole: "Senior Analyst",
        company: "Polestar Solutions",
        package: "10 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_analytics",
        isFeatured: false,
        testimonial: "I was looking to upgrade my skills and chose JVM Institute for Data Engineering training. It turned out to be one of the best decisions for my career.",
      },
      {
        name: "Karan Sagare",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Primotech",
        package: "10 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: "JVM Institute provides excellent training with supportive trainers and practical learning. The concepts are explained clearly, and the placement guidance is very helpful.",
      },
      {
        name: "Rahul",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Anchanto",
        package: "10 LPA",
        image: "/placements/placement_9_rahul.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " Coming from an Non IT background, I had limited technical knowledge. JVM Institute helped me understand Data Engineering concepts from scratch through hands-on learning and real-world projects. The trainers focused on practical implementation rather than just theory. The placement support and mock interviews played a huge role in my success. Thanks to JVM Institute, I was able to make a successful career transition into IT.",
      },
      {
        name: "Mansi Chaudhary",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Bitwise",
        package: "10 LPA",
        image: "/placements/placement_32_mansichaudhary.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " Coming from a marketing background, I always wanted to build a career in the IT industry but didn't know where to start. Joining JVM Institute was the best decision I made. The Data Engineering course was designed in a simple and practical way, making it easy for a non-technical person like me to learn SQL, Python, PySpark, and AWS. The trainers provided constant support, mock interviews, and real-time project experience. With their guidance, I successfully transitioned from Marketing to Data Engineering and secured a great job opportunity with a much better package. Thank you, JVM Institute, for helping me transform my career.",
      },
      {
        name: "Durgesh Jadhav",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Ascentt",
        package: "10 LPA",
        image: "/placements/placement_34_durgeshjadhav.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " As a non-IT graduate, I had very little technical knowledge when I joined JVM Institute. The trainers were incredibly supportive and ensured that every concept was understood clearly. The hands-on projects, assignments, and mock interviews prepared me for real-world challenges. The placement team guided me throughout the process. Today, I am working as a Data Engineer and enjoying a rewarding career in IT.",
      },
      {
        name: "Vivek Ingale",
        domain: "Data Engineering",
        placedRole: "Software Engineer",
        company: "Simple Logic",
        package: "9.5 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: "I joined JVM Institute to upgrade my skills in Data Engineering. The course was well-structured and covered all the latest technologies.",
      },
      {
        name: "Rushikesh Adhav",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Lumiq",
        package: "9 LPA",
        image: "/placements/placement_24_rushikeshadhav.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " I joined JVM Institute to upgrade my technical skills, and it was a great experience. The trainers are knowledgeable, supportive, and explain concepts clearly. The practical training and hands-on assignments helped me gain confidence and improve my skills. Thank you JVM Institute for contributing to my professional growth and career development.",
      },
      {
        name: "Sandesh Fule",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "Bitwise",
        package: "8 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: "Being a Civil Engineer, I was looking for better career growth opportunities. JVM Institute helped me upskill in Data Engineering and guided me through interviews.",
      },
      {
        name: "Trupti Musale",
        domain: "PySpark & Big Data",
        placedRole: "Coming From A Commerce Background, I Never Thought I Could Build A Career In The It Industry. I Was Looking For Better Career Opportunities But Didn'T Know Where To Start. After Joining Jvm Institute, I Learned Data Engineering From Scratch, Including Sql, Python, Pyspark, And Aws. The Trainers Were Very Supportive And Made Complex Concepts Easy To Understand. The Real-Time Projects, Mock Interviews, And Placement Assistance Helped Me Gain Confidence. With The Guidance Of Jvm Institute, I Successfully Transitioned From Commerce To Data Engineering And Secured A Great Job Opportunity. Thank You, Jvm Institute, For Helping Me Transform My Career.",
        company: "Softenger Pvt.Ltd",
        package: "6 LPA",
        image: "/placements/placement_27_truptimusale.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "pyspark_bigdata",
        isFeatured: false,
        testimonial: "The practical training, live projects, and continuous mentorship at JVM Institute played a crucial role in enhancing my technical skills and landing my dream IT job.",
      },
      {
        name: "Prasanth",
        domain: "Data Engineering",
        placedRole: "Software Developer",
        company: "Tcs",
        package: "4 LPA",
        image: "/placements/placement_37_prasanth.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " Before joining JVM Institute, I had basic technical knowledge but lacked the practical skills required for a Data Engineering career. The trainers guided me through SQL, Python, PySpark, and Cloud technologies with real-time projects. The personalized attention and regular mock interviews boosted my confidence. The placement support was excellent throughout the journey. Today, I am working as a Data Engineer and grateful to JVM Institute for helping me achieve my career goals.",
      },
      {
        name: "Kamlesh Gaikwad",
        domain: "Data Engineering",
        placedRole: "Senior Associate",
        company: "Cognizant",
        package: "10 LPA",
        image: "/placements/placement_28_kamleshgaikwad.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: " I was already working in the IT industry, but I realized that upgrading my skills was necessary for better growth. JVM Institute helped me learn advanced Data Engineering concepts, cloud technologies, and real-time project implementation. The trainers provided excellent guidance and interview preparation. With continuous practice and support, I gained confidence and secured a better opportunity with a higher package. Thank you JVM Institute for helping me grow professionally.",
      },
      {
        name: "Sagar Lahane",
        domain: "Data Analytics",
        placedRole: "Business Analyst",
        company: "Cognizant",
        package: "10 LPA",
        image: "/placements/placement_31_sagarlahane.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_analytics",
        isFeatured: false,
        testimonial: " I enrolled in JVM Institute to enhance my skills and prepare for better opportunities. The personalized attention and hands-on training helped me gain expertise in Data Engineering technologies.",
      },
      {
        name: "Pratiksha Raut",
        domain: "Data Engineering",
        placedRole: "Software Engineer",
        company: "Harman",
        package: "10 LPA",
        image: "/placements/placement_33_pratiksharaut.jpeg",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: "12.5 lakh I joined JVM Institute to upgrade my skills and stay competitive in today's fast-changing IT industry. The Data Engineering course provided hands-on training in SQL, Python, PySpark, AWS, and real-time projects. The trainers were knowledgeable, supportive, and always available to clear doubts. The mock interviews and placement preparation sessions significantly improved my confidence. With the skills I gained at JVM Institute, I was able to explore better career opportunities and achieve professional growth. I highly recommend JVM Institute to anyone looking to upskill and advance their career.",
      },
      {
        name: "Kenexai",
        domain: "Data Engineering",
        placedRole: "Data Engineer",
        company: "I Was Working As A Teacher And Wanted To Explore Better Career Opportunities In The It Industry. However, Coming From A Non-Technical Background, I Was Unsure How To Make The Transition. After Joining Jvm Institute, I Learned Data Engineering From The Ground Up, Including Sql, Python, Pyspark, And Aws. The Trainers Provided Excellent Guidance, Hands-On Projects, And Continuous Support Throughout My Journey. The Mock Interviews And Placement Assistance Helped Me Build Confidence And Prepare For The Industry. With The Support Of Jvm Institute, I Successfully Transitioned From Teaching To A Data Engineer Role With A Great Package. I Am Truly Grateful For This Life-Changing Opportunity.",
        package: "10 LPA",
        image: "/place1.png",
        skills: "SQL, Python, PySpark, Cloud Data Engineering",
        category: "data_engineering",
        isFeatured: false,
        testimonial: "The practical training, live projects, and continuous mentorship at JVM Institute played a crucial role in enhancing my technical skills and landing my dream IT job.",
      }
    ]
  });

  // Seed Courses
  await prisma.course.deleteMany();
  await prisma.course.createMany({
    data: [
      {
        slug: "data-engineering-master-program",
        title: "Data Engineering Master Program (PySpark & Databricks)",
        shortDescription: "Complete hands-on Data Engineering course covering Python, SQL, PySpark, Databricks, Snowflake & AWS.",
        fullDescription: "Master real-time data streaming, cloud data warehousing, and ETL pipeline building with 100% placement support.",
        duration: "6 Months",
        mode: "Online & Classroom (Karve Nagar, Pune)",
        fullFee: 45000,
        advanceFee: 5000,
        isFeatured: true,
      },
    ],
  });

  console.log("Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
